"""teachers.school_id nullable for phone-first signup before onboarding

Revision ID: 3e15203d0344
Revises: 43cb9d335b21
Create Date: 2026-08-20 15:30:38.926294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e15203d0344'
down_revision: Union[str, Sequence[str], None] = '43cb9d335b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'school_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'school_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
